version: 0.2
env:
  variables:
    ECR_REPO: angular-ecs
  parameter-store:
    DOCKERHUB_TOKEN: /dockerhub/token
    DOCKERHUB_USER: /dockerhub/user
phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - ECR_MAIN_URI="223798725213.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO}:latest"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}

  build:
    commands:
      - docker build -t my-angular-app:latest .
  post_build:
    commands:
      - docker tag my-angular-app:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}